In [1]:
import numpy as np
B = np.array ( [[0.21, -0.28, 0.05],
                [0.19, 0.01, -0.26],
                [0.39, -0.12, -0.06]] )
g = [-0.9, 3.8, -2.9]

In [2]:
q = [-0.9, 3.8, 2.9]

In [3]:
q = np.linalg.norm(B, np.inf)

In [4]:
#kiem tra dieu kien q=||B|| < 1
q

0.5700000000000001

In [5]:
#tim nghiem gan dung sau 3 buoc lap
x = [0, 2, -1]
for _ in range(3): 
    x= B.dot(x) + g
    print (x)

[-1.51  4.08 -3.08]
[-2.5135  4.3547 -3.7937]
[-2.836836  4.352344 -4.175207]


In [6]:
#danh gia sai so cua nghiem gan dung
x0 = [0, 2, -1]
for _ in range(3):
    x = B.dot(x0) + g
    ss = q / (1 - q) * np.linalg.norm(x - x0, np.inf)
    x0 = x
    print(x,ss)

[-1.51  4.08 -3.08] 2.7572093023255824
[-2.5135  4.3547 -3.7937] 1.3302209302325583
[-2.836836  4.352344 -4.175207] 0.5057185813953496


In [9]:
#tim nghiem gan dung ss 10^-3
x0 = [0, 2, -1]
k = 0
while True:
    x = B.dot(x0) + g
    ss = q / (1 - q) * np.linalg.norm(x - x0, np.inf)
    x0 = x
    k += 1
    print(k,x,ss)
    if ss < 10**-3:
        break


1 [-1.51  4.08 -3.08] 2.7572093023255824
2 [-2.5135  4.3547 -3.7937] 1.3302209302325583
3 [-2.836836  4.352344 -4.175207] 0.5057185813953496
4 [-2.92315223  4.39007842 -4.2781349 ] 0.13643930930232454
5 [-2.95699067  4.40081693 -4.31015069] 0.04485560770465101
6 [-2.96870432  4.40281912 -4.32271535] 0.01665548818430217
7 [-2.97235303  4.40388036 -4.32677006] 0.005374840480007469
8 [-2.97361914  4.40425194 -4.32807712] 0.0017326198843711153
9 [-2.97405442  4.40435493 -4.32853707] 0.0006097006850512354


In [10]:
x0 = [0, 2, -1]
x1 = B.dot(x0) + g

In [11]:
#Xac dinh so buoc lap can thuc hien de dat duoc nghiem co ss 10^-8 (cong thuc tien nghiem)
from sympy import log
log( 10**-8 * (1-q) / np.linalg.norm(x1 - x0, np.inf), q)

35.5743563544289

In [13]:
#Dung cong thuc gauss seidel tim nghiem gan dung sau 4 buoc lap
x = [0, 2, -1]
for _ in range(4):
    for i in range(3):
        x[i] = B[i].dot(x) + g[i]
    print(x)

[-1.5100000000000002, 3.7931, -3.8840719999999997]
[-2.4733716, 4.377849116, -4.1569124979200005]
[-2.8530514133760003, 4.38249597207776, -4.289174817990771]
[-2.9406984098902718, 4.400277714519227, -4.317555216520067]


In [14]:
#he cheo troi (go phan nay trc sau do go tu tren xuong)
A = [[-15.4, 1, 6.3], [-4.2, 10.8, 3.3], [-2.4, 5.3, 15.9]]
b = [30, 25, -10]

In [15]:
m = lambda i, j: -A[i][j] / A[i][i] if i != j else 0
import numpy as np
B = np.array([ [m(i, j) for j in range(3)] for i in range(3) ])

In [16]:
g = [ b[i] / A[i][i] for i in range(3) ]

In [17]:
g

[-1.948051948051948, 2.314814814814815, -0.6289308176100629]